#!/bin/bash
# Script original name: daemon-start4node/start-stop/go
# Copyright 2021 Alexander R Danel

# Purpose:
#   This is a launch script for testing while in "dev" environment.
#
# Recommended usage:
#
#   Presuming product is called ${MY_APP_NM}, and
#   presuming top level directory for development of product is
#             ~/${MY_APP_NM}
#
#   Copy entire subdirectory daemon-start4node/start-stop into the dev dir.
#
# $ (cd ${DAEMON-START4NODE}; tar cf - start-stop) | (cd ~/${MY_APP_NM}; tar xvf - )
#
#   So you now have
#             ~/${MY_APP_NM}/start-stop
#
#   The configuration directory is called "sysconfig".  Go there.
#
# $ cd ~/${MY_APP_NM}/start-stop/sysconfig
#
#   System level configuration for your server will be performed through 
#   environment variables.  Any parameter that changes according to where
#   the server is running (which machine, which environment) should be an
#   environment variable in the "sysconfig".  If your server doesn't work 
#   that way, then modify the server code.
#
#   Make a local copy of the config file, giving it a name that follows
#   the convention that the name has "node4" prepended to the server name,
#   but also add a suffix of "-dev" to clarify this is a particular instance
#   of the config which is applicable only to the "dev" environment.
#
# $ cp node4_xxxx_-sample node4${MY_APP_NM}-dev
#
#   Note that at some later date, you will probably create other versions of 
#   the config, with suffixes that suggest what environment they are for.
#   For example:
#       node4${MY_APP_NM}-test
#       node4${MY_APP_NM}-prod
#
#   Now, make a symbolic link that has a name exactly matching the name that 
#   will be used in the "init.d".  (The only difference between the link name 
#   versus the file name is that for the link, the suffix "-dev" is omitted).
#
# $ ln -s node4${MY_APP_NM}-dev node4${MY_APP_NM}
#
#   Edit the configuration file, and put in all environment variables needed
#   to run the program you are developing.
#
# $ vi ~/${MY_APP_NM}/start-stop/sysconfig/node4${MY_APP_NM}-dev
#  ... (do the edit) ...
#
#   Development occurs in the server dir.
#
# $ cd ~/${MY_APP_NM}/server
#
#   Copy the "go" script into server development area. "start-stop" -> "server"
#
# $ cp  ~/${MY_APP_NM}/start-stop/go  ~/${MY_APP_NM}/server/go
#
#   Adjust the script parameters "MY_APP_NM" and "START_STOP_DIR".
#
# $ vi  ~/${MY_APP_NM}/server/go
#  ... (do the edit) ...
#
#   That completes set up.
#
#   Use the script to start and stop the server:
#
# $ ./go status
# $ ./go start
# $ ./go stop
# $ ...etc...
#

#set -x

declare MY_APP_NM="_xxxx_"
declare daemonName="node4${MY_APP_NM}"

#declare START_STOP_DIR="$HOME/Goog_Drv/repos/${MY_APP_NM}/start-stop";
declare START_STOP_DIR="$HOME/${MY_APP_NM}/start-stop";

# Set and export environment variables
export daemonSysconfigName="$START_STOP_DIR/sysconfig/${daemonName}-dev";
export WEB_DIR="$HOME/${MY_APP_NM}/web-server"; # or wherever you put the server code

# Execute the script that launches the server daemon
"$START_STOP_DIR/init.d/${daemonName}" "$@"

