#!/bin/sh                        <= Inform text editor: highlight as shell code
# File: 
#   ..../start-stop/sysconfig/node4_xxx-utest-com     (name in repository)
#              /etc/sysconfig/node4_xxx              (installed name)
#
# Based upon "daemon-start4node/sysconfig/node4_xxx-zapp-com"
# That file is copyright 2020 Alexander R Danel
# MIT License

# Note: This script is intended to be "sourced," (not executed directly).

# vvvvvvvvvvvvvvvvvvvvvvv  Set environment variables  vvvvvvvvvvvvvvvvvvvvvvvvvv

declare MY_APP_NM="selfsign"
declare DNS_SHORT_NM="utest-com"
declare DB_CHOICE="test";
declare DEV_REPOSITORY="(not applicable)";

# for setting other vars within this file ______________________________________
: ${daemonName:?"must be defined before sourcing sysconfig"}

# for both daemon-launcher and 'node' app ______________________________________
export nodeListenPort="443";

# for daemon-launcher __________________________________________________________

# The javaScript file that "node" should run.
export  nodeServerMainJs=index.js

# The directory hierarchy
declare         VAR="/var"
declare         OPT="/opt"
export      LOG_DIR="$VAR/log/${daemonName}";
export      PID_DIR="$VAR/run";
export WEB_ROOT_DIR="$OPT/web/";
export APP_ROOT_DIR="${WEB_ROOT_DIR}/${MY_APP_NM}";
export   SERVER_DIR="${APP_ROOT_DIR}/server";

# for 'node' app _______________________________________________________________
export isSSL="no";

# SSL certificate information, for 'node' app
export sslCertificateDir="/etc/pki/tls/certs";
export sslCertPrivateDir="/etc/pki/tls/private";

# The 'key' and 'cert' are required for 'https'
export ssl_cert="${sslCertificateDir}/ct.planner9.com.crt"
export  ssl_key="${sslCertPrivateDir}/ct.planner9.com.key"

# The 'ca' (certificate authority) information is optional
export ssl_ca_1=""
export ssl_ca_2=""

# additional_vars ______________________________________________________________

# for 'node' app ...
export        whichEnv="test";		# dev|test|prod
export isServerDevMode="yes";
export target_hostname="ct.planner9.com";

# Summary of "additional_vars"; this gets passed to 
# the "showConfig" function in the launch script "init.d/node4___"
export additional_vars="
  whichEnv
  isServerDevMode
  target_hostname
";

# ^^^^^^^^^^^^^^^^^  Finished setting environment variables  ^^^^^^^^^^^^^^^^^^^

