#!/bin/sh                        <= Inform text editor: highlight as shell code
# The template file is copyright 2021 Alexander R Danel
# Please retain copyright notice in derived works (which may have their
# own additional copyright).
# MIT License
#
# Template for a config file that serves the development environment where the
# server is run on the developers machine and accessed as localhost 127.0.0.1.
#
# Name of template file:
#   ..../start-stop/sysconfig/node4_xxxx_-website-com
#
# In the TEST or PROD environments, config is used by "/etc/init.d" script,
# so put the customized version where that script expects to look find it:
#       /etc/sysconfig/node4_xxxx_

# Note: This script is intended to be "sourced," (not executed directly).

# vvvvvvvvvvvvvvvvvvvvvvv  Set environment variables  vvvvvvvvvvvvvvvvvvvvvvvvvv

declare MY_APP_NM="_xxxx_"
declare DNS_SHORT_NM="my_website-com"
declare DB_CHOICE="prod";
declare DEV_REPOSITORY="(not applicable)";

# for setting other vars within this file ______________________________________

# Note that when called by matching "/etc/init.d/node4_xxxx_" script, 
# the value of "$daemonName" will be set by that script,
# so that context should never result in an error here.
: ${daemonName:?"must be defined before sourcing sysconfig"}

# for both daemon-launcher and 'node' app ______________________________________
export nodeListenPort="443";

# for daemon-launcher __________________________________________________________

# The javaScript file that "node" should run.
export  nodeServerMainJs=index.js

# The directory hierarchy
declare         VAR="/var"
declare         OPT="/opt"
export      LOG_DIR="$VAR/log/${daemonName}";
export      PID_DIR="$VAR/run";
export WEB_ROOT_DIR="$OPT/web/";
export APP_ROOT_DIR="${WEB_ROOT_DIR}/${MY_APP_NM}";
export   SERVER_DIR="${APP_ROOT_DIR}/server";

# for 'node' app _______________________________________________________________

# Here are some suggested variables that the server program might want to 
# incorporate.
export isSSL="yes";

# SSL certificate information, for 'node' app
export sslCertificateDir="/etc/pki/tls/certs";
export sslCertPrivateDir="/etc/pki/tls/private";

# The 'key' and 'cert' are required for 'https'
MY_HOSTNAME="my_website.com";
export ssl_cert="${sslCertificateDir}/${MY_HOSTNAME}.crt"
export  ssl_key="${sslCertPrivateDir}/${MY_HOSTNAME}.key"

# The 'ca' (certificate authority) information is optional
export ssl_ca_1=""
export ssl_ca_2=""

# additional_vars ______________________________________________________________

# App specific config, not used by the start-stop script.
# Set any additional env vars that will be used by the server app.
# (In template file, these are just examples.  Replace with your own.)
export        whichEnv="prod";		# dev|test|prod
export isServerDevMode="no";
export target_hostname="${MY_HOSTNAME}";

# Summary of "additional_vars"; this gets passed to 
# the "showConfig" function in the launch script "init.d/node4_xxxx_"
export additional_vars="
  whichEnv
  isServerDevMode
  target_hostname
";
# pathToConnectionConfig <= not used?

# ^^^^^^^^^^^^^^^^^  Finished setting environment variables  ^^^^^^^^^^^^^^^^^^^

